USE [master]
GO
/****** Object:  Database [db_raza_bordir]    Script Date: 24/12/2024 19:51:49 ******/
CREATE DATABASE [db_raza_bordir]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_raza_bordir', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_raza_bordir.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_raza_bordir_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_raza_bordir_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_raza_bordir] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_raza_bordir].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_raza_bordir] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_raza_bordir] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_raza_bordir] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_raza_bordir] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_raza_bordir] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_raza_bordir] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_raza_bordir] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_raza_bordir] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_raza_bordir] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_raza_bordir] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_raza_bordir] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_raza_bordir] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_raza_bordir] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_raza_bordir] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_raza_bordir] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db_raza_bordir] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_raza_bordir] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_raza_bordir] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_raza_bordir] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_raza_bordir] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_raza_bordir] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_raza_bordir] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_raza_bordir] SET RECOVERY FULL 
GO
ALTER DATABASE [db_raza_bordir] SET  MULTI_USER 
GO
ALTER DATABASE [db_raza_bordir] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_raza_bordir] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_raza_bordir] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_raza_bordir] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_raza_bordir] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_raza_bordir] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'db_raza_bordir', N'ON'
GO
ALTER DATABASE [db_raza_bordir] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_raza_bordir] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_raza_bordir]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 24/12/2024 19:51:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[admin_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [char](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[admin_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 24/12/2024 19:51:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[customer_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[phone] [varchar](15) NOT NULL,
	[password] [char](60) NOT NULL,
	[address] [varchar](100) NOT NULL,
	[age] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 24/12/2024 19:51:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[order_id] [int] IDENTITY(1,1) NOT NULL,
	[amount] [int] NOT NULL,
	[total_price] [decimal](8, 2) NOT NULL,
	[order_date] [date] NOT NULL,
	[notes] [text] NOT NULL,
	[product_id] [int] NOT NULL,
	[customer_id] [int] NOT NULL,
	[design] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 24/12/2024 19:51:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[product_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[description] [text] NOT NULL,
	[start_price] [decimal](7, 2) NOT NULL,
	[image] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[product_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reviews]    Script Date: 24/12/2024 19:51:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reviews](
	[review_id] [int] IDENTITY(1,1) NOT NULL,
	[review] [text] NULL,
	[date_post] [date] NOT NULL,
	[rating] [int] NOT NULL,
	[order_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[review_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([customer_id])
REFERENCES [dbo].[Customers] ([customer_id])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[Products] ([product_id])
GO
ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD FOREIGN KEY([order_id])
REFERENCES [dbo].[Orders] ([order_id])
GO
USE [master]
GO
ALTER DATABASE [db_raza_bordir] SET  READ_WRITE 
GO
